### ISSUE TITLE
Consider the depth of the nest

### ISSUE THREAD

**Issue by sotayamashita** [necolas/idiomatic-css#87]
When we use preprocessors such as SCSS, we can use **nesting**. It is very powerful feature but it will cause confusion depending on the depth of the nest.

**Comment by JamyGolden** [comment]
@sotayamashita I think that would fall more along the lines of a CSS methodology like [BEM](http://nicolasgallagher.com/about-html-semantics-front-end-architecture/) or [OOCSS](http://www.slideshare.net/stubbornella/object-oriented-css/). With BEM you could use [Sass's @at-root](http://una.im/2013/10/15/sass-3-3-at-root-bem.html) and nest the classes, but have them compile as not-nested.
